### ISSUE TITLE
Not able to recreate a table,

### ISSUE THREAD

**Issue by sk8Guerra** [hennessyevan/gatsby-remark-grid-tables#5]
I'm trying to create a table like this: 

<img width="204" alt="Screen Shot 2021-08-09 at 14 47 50" src="https://user-images.githubusercontent.com/18681676/128772339-38d2bc54-80db-45c5-ba4e-3b59a849b69f.png">

This way:
<img width="154" alt="Screen Shot 2021-08-09 at 14 52 46" src="https://user-images.githubusercontent.com/18681676/128772924-c74dbaeb-fffd-4694-a9cd-87744395097f.png">

But the desired result is not correct:

<img width="239" alt="Screen Shot 2021-08-09 at 14 53 18" src="https://user-images.githubusercontent.com/18681676/128772992-65afa793-87c6-44f2-8382-6923ddd60267.png">
 
Because there is still a division in the last cell.

Is this supported?

**Comment by hennessyevan** [comment]
That's a really interesting use case. I've certainly never tried something like that. I would however ask this question in the https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-grid-tables repo, this package only provides a very simple wrapper over that package to easily include it in gatsby's plugin chain.

**Comment by sk8Guerra** [comment]
Then I'll ask in that repo, thanks @hennessyevan!
